sudo: false  # Force container-based builds.
language: python

cache:
  - pip
before_install:
  - pip install --upgrade pip
install:
  - pip install -e .
  - pip install -r requirements/dev.txt
script:
  - black . --check
  - flake8 .
  - py.test

jobs:
  include:
    - stage: test
      python: "3.6"
      # Clear unused build steps
      services: []
      deploy: []
      after_success: []
    - stage: docker
      python: "3.6"
      sudo: required
      dist: trusty
      services: [docker]
      env:
        - IMAGE_NAME=praekeltfoundation/lebombo
        - REGISTRY_USER=praekeltorgdeploy
        - secure: "ijm/JQjn2fZmEAMuPztjfubTBFy3YEmAE8UKjqDp/jx8zguf/AWN/oQro7JYj0fvseUoAS+8QW8w8r+nwebrOMVxg0gxN9PEXOnuUCvYxPmoa3jFXq+pfvwZlYGvkFBcxyLPzfkss3AQRV+ykuWzK6jf0qDO5WCZg/E2oXDsaChOQWzE8p0ou+j/2VMvn94LlfIQ5y5E3e0OFinfcSS0enskZmtH+n441jTuquVCDQh+6czc8kifEkKfwYFDbaEdWd4hHaRYJTUnM1cE4lpk3gO+7MWN4b1uxV32PeJCHwHzGNmLd3N6d38ryoH3Vt7X04B82dqy9RlTQzRVW5cH5o4Lta66cK+z3qMse8lQLkCDucG3bTB4V92Th5B6xO8OwR53915JaZeVy2d+Ae4aijWr34JsrBI18uuMbDCDM+qyHXGVqFBHQyRrC1EMiTzcHY+iaFJJsaloQb1A8RYN9cwWQVggyKSXpUkapLTL88hWI7VU0WnttM5NUBX0fZonaHjlkzaerUyzN0XYgJZiiMOIY6+9ikkAhRoIUIvQEGjuxFP4uyBcjofqTuQgKehHXj3W2/HjtXM9d2hUpD7WfQKdStorAt2OclMB7Q6mHSVT4rzODbRRlNvZpJ+n3PuCku8vTVw24UOgz2MxDA3ZxQ82xpMdpce2+/91L+0Hdrg="  # yamllint disable-line

      before_script:
        - docker pull "$IMAGE_NAME" || true
      script:
        - docker build --pull --tag "$IMAGE_NAME" .

      before_deploy:
        - pip install docker-ci-deploy==0.3.0
        - echo -n $REGISTRY_PASS | docker login --username "$REGISTRY_USER" --password-stdin # yamllint disable-line
      deploy:
        - provider: script
          script: dcd --version "$(git rev-parse --short HEAD)" --version-latest "$IMAGE_NAME" # yamllint disable-line
          on:
            branch: develop
        - provider: script
          script: dcd --tag "$TRAVIS_TAG" -- "$IMAGE_NAME"
          on:
            tags: true

      # Built steps inherited from the default stage that we don't want
      before_install: ignore
      after_success: []
